app:
    jwt:
        # Use a strong secret key in production
        secret: test-carhov6765478654SecureSecretKeyForJwtAuthenticationAndAuthorization
        expirationMs: 3600000      # 1 hour
        refreshExpirationMs: 86400000   # 24 hours
    nonce:
        expirationMs: 86400000   #24 hours